//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.InteropServices;
using Microsoft.Office.Interop.Excel;
using Telerik.WinControls;

namespace rehber
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.Drawing;
    using System.IO;
    using System.Windows.Forms;
    using System.Linq;
    using System.Globalization;

    public partial class FrmRehber : BaseRadForm
    {

        public FrmRehber()
        {
            InitializeComponent();
            this.Text = KullaniciBilgi.KullaniciAdi + " - REHBER";
        }

        private List<RehberModel> _rehberList;

        ///
        //>    FrmRehber_Load
        ///
        private void FrmRehber_Load(object sender, System.EventArgs e)
        {
            listele();

            RehberModel selectedItem = this.lstRehber.SelectedItem as RehberModel;

            AutoCompleteStringCollection listBoxStrings = new AutoCompleteStringCollection();

            foreach (RehberModel model in this._rehberList)
            {
                listBoxStrings.Add(model.Isim + " " + model.Soyisim);
                this.lstRehber.SelectedItem = model.Isim + " " + model.Soyisim;
            }

            this.txtAra.AutoCompleteCustomSource = listBoxStrings;

            controlsEnableOrNot();
            
        }

        ///
        //->    btnSil_Click
        ///
        private void btnSil_Click(object sender, System.EventArgs e)
        {
            if(lstRehber.Items.Count==0)
            {
                RadMessageBox.SetThemeName("TelerikMetro");
                RadMessageBox.Show("Silinecek kayýt yok!", "Sil", MessageBoxButtons.OK, RadMessageIcon.Info);
            }
            else if (MessageBox.Show("Kayýdý silmek istediðinize emin misiniz ?", "Sil", MessageBoxButtons.YesNo) == DialogResult.Yes)
            {
                
                try
                {
                    SqlConnection connection = new SqlHelper().Connection();
                    connection.Open();

                    RehberModel selectedItem = this.lstRehber.SelectedItem as RehberModel;
                    new SqlCommand("DELETE FROM dbo.rehber WHERE rehber.ID = " + selectedItem.Id, connection).ExecuteNonQuery();
                    this.pictureBoxGoster.Image = image.icon_user_default;
                    this.labelAdSoyad.Text = null;
                    this.labelTelefon.Text = this.labelDogumTarihi.Text = this.labelCinsiyet.Text = this.txtIsTanimi.Text = string.Empty;
                    this.listele();
                    controlsEnableOrNot();

                    RadMessageBox.SetThemeName("TelerikMetro");
                    RadMessageBox.Show("Kayýt silindi!", "Sil", MessageBoxButtons.OK, RadMessageIcon.Info);

                   connection.Close();

                }
                catch (Exception exception)
                {
                    MessageBox.Show(exception.Message);
                }
            }

        }

        ///
        //->   buttonGuncelle_Click
        ///
        private void btnGuncelle_Click(object sender, System.EventArgs e)
        {
                if (lstRehber.Items.Count == 0)
                {
                    RadMessageBox.SetThemeName("TelerikMetro");
                    RadMessageBox.Show("Listede henüz kayýt yok.", "Güncelle", MessageBoxButtons.OK, RadMessageIcon.Info);
                }
                else
                {
                    RehberModel selectedItem = this.lstRehber.SelectedItem as RehberModel;
                    new FrmUpdate(selectedItem).ShowDialog();
                    this.listele();
                }
            
        }

        ///
        //->   listBox1_SelectedIndexChanged  -> listede seçili eleman deðiþtiðinde..
        ///
        private void lstRehber_SelectedIndexChanged(object sender, System.EventArgs e)
        {
            this.goster();
        }

        ///
        //->   listBox1_DoubleClick
        ///
        private void lstRehber_DoubleClick(object sender, System.EventArgs e)
        {
            RehberModel selectedItem = this.lstRehber.SelectedItem as RehberModel;
            new FrmUpdate(selectedItem,this).ShowDialog();
        }

        ///
        //->   textBoxAra_TextChanged -> arama yaparken sonuçlarý anlýk gösterebilmek için..
        ///
        private void txtAra_TextChanged(object sender, System.EventArgs e)
        {
            List<RehberModel> list = (from q in this._rehberList
                                      where ((q.Isim.Contains(this.txtAra.Text) | q.Soyisim.Contains(this.txtAra.Text)) | q.GenelBilgi.Contains(this.txtAra.Text)) | q.TelNo.Contains(this.txtAra.Text)
                                      select q).ToList<RehberModel>();
           

            if (list.Count == 0)
            {
                this.pictureBoxGoster.Image = image.icon_user_default;
                this.labelAdSoyad.Text = "...";
                this.labelTelefon.Text = this.labelDogumTarihi.Text = this.labelCinsiyet.Text = this.txtIsTanimi.Text = "-";
                lblLBStatus.Text = "Kayýt Bulunamadý !!";

                lblLBStatus.ForeColor = Color.Red;
            }
            else
            {
                this.lstRehber.DataSource = list;
                lblLBStatus.Text = "Toplam Kayýt: " + list.Count; 
                lblLBStatus.ForeColor = Color.Black;
            }

            this.lstRehber.DataSource = list;
        }


        ///
        //->   buttonYeniKayit_Click
        ///
        private void btnYeniKayit_Click(object sender, System.EventArgs e)
        {
            new FrmNewPerson(this).ShowDialog();
        }

        ///
        //->   listele() -> kaydedilen isimler listbox ta listeleniyor.
        ///
        public void listele()
        {
            this.lstRehber.ValueMember = "kullaniciID";
            this.lstRehber.DisplayMember = "GenelBilgi"; // GenelBilgi, RehberModel'in içinde "Ýsim + Soyisim" bilgisini tutan eleman.
            this._rehberList = new RehberBL().RehberList();
            this.lstRehber.DataSource = this._rehberList;

            lblLBStatus.Text = "Toplam Kayýt: " + _rehberList.Count;
        }

        ///
        //->   goster()  -> FrmRehber formunun sað tarafýnda bilgiler gösteriliyor.
        ///
        public void goster()
        {
            RehberModel selectedItem = this.lstRehber.SelectedItem as RehberModel;
            if (selectedItem != null)
            {
                if (selectedItem.Resim != null)
                {
                    MemoryStream stream = new MemoryStream(selectedItem.Resim);
                    this.pictureBoxGoster.Image = Image.FromStream(stream);
                }
                else
                {
                    this.pictureBoxGoster.Image = null;
                }

                //labelAdSoyad labelinin yazý boyutunu kontrol ediyor
                if (selectedItem.GenelBilgi.Length < 19)
                {
                    this.labelAdSoyad.Font = new Font("candara", 18, FontStyle.Regular);
                    this.labelAdSoyad.TextAlignment = ContentAlignment.MiddleLeft;
                }
                else if (selectedItem.GenelBilgi.Length >= 19 && selectedItem.GenelBilgi.Length < 25)
                {
                    this.labelAdSoyad.Font = new Font("candara", 15, FontStyle.Regular);
                    this.labelAdSoyad.TextAlignment = ContentAlignment.MiddleLeft;
                }
                else 
                {
                    this.labelAdSoyad.Font = new Font("candara", 12, FontStyle.Regular);
                    this.labelAdSoyad.TextAlignment = ContentAlignment.MiddleLeft;
                }

                this.labelAdSoyad.Text = ToTitleCase(selectedItem.GenelBilgi); 
                this.labelTelefon.Text = selectedItem.TelNo;
                this.labelEMail.Text = selectedItem.EMail;
                this.labelDogumTarihi.Text = selectedItem.DogumTarihi.ToShortDateString();
                this.labelCinsiyet.Text = selectedItem.Cinsiyet;
                this.txtIsTanimi.Text = selectedItem.IsTanimi;
            }
        }
        ////
        //--> controlsEnableOrNot() -> "Ara" text box ýný ve "excel'e aktar" butonunu kayýt varken açýp kayýt yokken kapatýr.
        ////
        public void controlsEnableOrNot() 
        {
            if (this.lstRehber.Items.Count == 0)
            {
                this.txtAra.Enabled = false;
                this.btnExcelAktar.Enabled = false;
            }
            else
            {
                this.txtAra.Enabled = true;
                this.btnExcelAktar.Enabled = true;
            }

        }

        ////
        //--> btnKullaniciDegistir_Click() -> baþka kullanýcýya geçmek için.. 
        ////
        private void btnKullaniciDegistir_Click(object sender, EventArgs e)
        {
            RadMessageBox.SetThemeName("TelerikMetro");
            DialogResult result = RadMessageBox.Show("Baþka kullanýcýya geçmek istediðinize emin misiniz?", "Kullanýcý Deðiþtir", MessageBoxButtons.YesNo, RadMessageIcon.Question);

            if (result == DialogResult.Yes)
            {
                this.Hide();    
                FrmLogin _frmLogin = new FrmLogin();
                _frmLogin.ShowDialog();
                this.Close();

            }
           
        }

        ////
        //--> btnExcelAktar_Click() -> verileri excel e aktaran buton 
        ////
        private void btnExcelAktar_Click(object sender, EventArgs e)
        {
            new ImportExcelCheckList(this.lstRehber).ShowDialog();
        }

        public void lblSifreDegistir_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
        {

            
           
        }

        private void btnMailGonder_Click(object sender, EventArgs e)
        {
            var frmEPosta = new Frm_ePostaOlustur();
            frmEPosta.ShowDialog();
        }

        public static string ToTitleCase(string value)
        {
            return CultureInfo.CurrentCulture.TextInfo.ToTitleCase(value);
        }

        private void btnSplitSifreDegistir_Click(object sender, EventArgs e)
        {
            FrmChangePassword _frmChangePassword = new FrmChangePassword();

            _frmChangePassword.ShowDialog();
        }

        private void btnSplitEMailDegistir_Click(object sender, EventArgs e)
        {
            FrmChangeEmailAddress _frmChangeEmail = new FrmChangeEmailAddress();
            _frmChangeEmail.ShowDialog();
        }

    }
}
