
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace rehber
{

using System;
    using System.Collections.Generic;
    
public partial class login
{

    public login()
    {

        this.rehbers = new HashSet<rehber>();

    }


    public int kullaniciID { get; set; }

    public string kullaniciAdi { get; set; }

    public string sifre { get; set; }

    public Nullable<bool> beniHatirla { get; set; }

    public string kullaniciEMail { get; set; }



    public virtual ICollection<rehber> rehbers { get; set; }

}

}
